export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export const SOCIAL_LOGIN_PASS = 'SOCIAL_LOGIN_PASS';
export const SOCIAL_LOGIN_FAIL = 'SOCIAL_LOGIN_FAIL';
